# Generated by Django 3.2.7 on 2021-09-12 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_question', models.TextField()),
                ('asked_when', models.DateTimeField(auto_now_add=True)),
                ('type_of_question', models.TextField(blank=True, default='main', null=True)),
                ('asked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='User_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
                ('profession', models.CharField(blank=True, max_length=15, null=True)),
                ('short_bio', models.CharField(max_length=200)),
                ('knows_about', models.TextField(blank=True, null=True)),
                ('the_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='the_user_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sub_question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_sub_question', models.TextField()),
                ('is_answered', models.BooleanField(default=False)),
                ('main_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_answer', models.TextField()),
                ('answered_when', models.DateTimeField(auto_now_add=True)),
                ('answer_of', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='question.question')),
                ('answer_of_sub', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='question.sub_question')),
                ('answered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
