# Generated by Django 3.2.7 on 2021-09-12 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_auto_20210912_1919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type_of_question',
        ),
    ]
