# Generated by Django 3.2.7 on 2021-09-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_alter_user_profile_short_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_category',
            field=models.CharField(default='jdgf', max_length=30),
            preserve_default=False,
        ),
    ]
