# Generated by Django 3.2.7 on 2021-09-15 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20210914_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
