# Generated by Django 3.2.7 on 2021-09-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_auto_20210915_0622'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='question',
            name='up_votes',
        ),
        migrations.AddField(
            model_name='answer',
            name='down_votes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answer',
            name='up_votes',
            field=models.IntegerField(default=0),
        ),
    ]
