# Generated by Django 3.2.7 on 2021-09-15 07:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('question', '0008_auto_20210915_0624'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='downvoted_user',
            field=models.ManyToManyField(related_name='downvotedUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='answer',
            name='upvoted_user',
            field=models.ManyToManyField(related_name='upvotedUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
