# Generated by Django 3.2.7 on 2021-09-15 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20210915_0756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='down_votes',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='up_votes',
        ),
    ]
