# Generated by Django 3.2.7 on 2021-09-16 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0014_answer_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_profile',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
