# Generated by Django 3.2.7 on 2021-09-16 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0015_user_profile_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
