# Generated by Django 3.2.7 on 2021-09-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0016_alter_user_profile_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='fun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(default=1)),
            ],
        ),
    ]
